name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --force

      - name: Create downloads directory
        run: mkdir -p public/downloads

      - name: Create sample files
        run: |
          echo "Sample APK file" > public/downloads/controlbovino.apk
          echo "Sample EXE file" > public/downloads/controlbovino.exe

      - name: Build
        run: npm run build

      - name: Add .nojekyll file
        run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
